---
title: "nlcd_oba"
author: "egb"
date: "2024-11-20"
output: html_document
---
```{r load-libraries, echo=FALSE, results="hide", message=FALSE, warning=FALSE}
library(terra)
library(ggplot2)
library(dplyr)
library(sf)
```


# OBA MANIPULATION

```{r oba-import}

# Import OBA data:

oba <-
  read.csv("data/OBA_2018-2023_combined_dataset_working.csv")

```

```{r}
# Segment OBA data: 

# - Metadata we need:
#   - `Species`: The taxonomic identification of each bee (group of closely related species)
#   - `Genus`: The taxonomic identification of each bee (specific type within Genus)
#   - `Elevation`: The elevation (in meters) at which each bee was collected.
#   - `Coordinates`: Latitude (`Dec.Lat.`) and longitude (`Dec.Long.`) in decimal degrees.


# Subset oba data to our needed metadata
oba <- select(oba, Genus, Species, Dec..Lat., Dec..Long., Elevation..m.)
colnames(oba) <- c("Genus", "Spec", "Lat", "Long", "Elev")

# head(oba, 60)

# row count before cleaning: 195788
# nrow(oba)

```


```{r}
# Clean OBA data

# Remove elevation rows with null values 

for (col in colnames(oba)) {
  oba <- oba[oba[[col]] != "", ]
  oba <- oba[!is.na(oba[[col]]), ]
}
# Number of rows after cleaning: 41643
nrow(oba)

head(oba, 10)
```



```{r}
# Combine genus & species 
GenusSpec <- paste(oba$Genus, oba$Spec, sep=" ")

oba <- oba %>%
  mutate(GenusSpec)

colnames(oba)

head(oba, 10)
```


# NLCD MANIPULATION 

```{r nlcd-import, include=FALSE}

library(terra)
library(ggplot2)


# Observe the dataset metadata here: https://www.arcgis.com/sharing/rest/content/items/9bbaa64718774bbfbf5c6ade0edf86d3/info/metadata/metadata.xml?format=default&output=html 

# Load landcover data as raster 
nlcd <- rast("data/NLCD_2016_Land_Cover_OR/NLCD_2016_Land_Cover_OR.img")

# Aggregate the resolution so it loads faster 
# 'fact' defines the aggregation factor (e.g., 2 means 2x2 cells are combined into 1)
nlcd <-aggregate(nlcd, fact = 20, fun = "median")

# Check resolution
res(nlcd)



#convert the rast to a SpatVector
nlcd_poly = as.polygons(nlcd) |> 
  st_as_sf()

# --- Convert NLCD Raster to Polygons ---
# nlcd_polygons <- as.polygons(nlcd, dissolve = TRUE)




nlcd_filtered <- nlcd_poly
nlcd_filtered$LandType <- ifelse(nlcd_filtered$Layer == 43, "Mixed Forest",
                          ifelse(nlcd_filtered$Layer == 71, "Grassland", NA))

# Remove polygons that are not of interest
nlcd_filtered <- nlcd_filtered[!is.na(nlcd_filtered$LandType), ]


# Reproject crs to maintain consistency between datasets 
nlcd_filtered <- project(nlcd_filtered, crs("EPSG:4326"))


nlcd_df <- as.data.frame(nlcd_filtered, )
# Filter for specific classes
# Credit to figure out how to subset the large nlcd dataset: ChatGPT
nlcd_df <- classify(nlcd, rcl = matrix(c(-Inf, 42, NA,
43, 43, 43, 44, 70, NA,
71, 71, 71, 72, Inf, NA),
ncol=3, byrow=TRUE))

# Reproject crs to maintain consistency between datasets 
nlcd <- project(nlcd, crs("EPSG:4326"))

# Convert raster to data frame for plotting 
nlcd_df <- as.data.frame(nlcd, na.rm = TRUE, xy = TRUE)

# Add land cover type labels
nlcd_df <-nlcd_df %>%
  mutate(LandType = case_when(
    Layer_1 == 43.0 ~ "Mixed Forest",
    Layer_1 == 71.0 ~ "Grassland"
  )) %>%
  filter(!is.na(LandType))

# Observe dataframe columns 
head(nlcd_df)

```

